# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile
# Also ~/software/Arduino-Makefile
#
# --- nano ide 1.6
BOARD_TAG   = nano
BOARD_SUB   = atmega328
#ARDUINO_DIR = /cygdrive/c/Program\ Files\ (x86)/Arduino
#ARDUINO_DIR = ${HOME}/Arduino
#ARDUINO_DIR = ../../../Arduino
#ARDUINO_DIR = ~/Arduino
#ARDUINO_DIR = 'C:/Progra~2/Arduino'
#ARDUINO_DIR = /Progra~2/Arduino
ARDUINO_DIR = '/Progra~2/Arduino'
include ${HOME}/software/Arduino-Makefile/Arduino.mk
